// Categories
export const REQUEST_ALL_CATEGORIES = 'REQUEST_ALL_CATEGORIES';
export const RECEIVE_ALL_CATEGORIES = 'RECEIVE_ALL_CATEGORIES';
// Posts
export const REQUEST_ALL_POSTS = 'REQUEST_ALL_POSTS';
export const RECEIVE_ALL_POSTS = 'RECEIVE_ALL_POSTS';
export const ADD_NEW_POST = 'ADD_NEW_POST';
export const EDIT_POST = 'EDIT_POST';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
