// Categories
export const REQUEST_ALL_CATEGORIES = 'REQUEST_ALL_CATEGORIES';
export const RECEIVE_ALL_CATEGORIES = 'RECEIVE_ALL_CATEGORIES';
// Posts
export const REQUEST_ALL_POSTS = 'REQUEST_ALL_POSTS';
export const RECEIVE_ALL_POSTS = 'RECEIVE_ALL_POSTS';
export const ADD_NEW_POST = 'ADD_NEW_POST';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
export const GET_POST_BY_ID = 'GET_POST_BY_ID';
// Comments
export const REQUEST_ALL_COMMENTS = 'REQUEST_All_COMMENTS';
export const RECEIVE_ALL_COMMENTS = 'RECEIVE_ALL_COMMENTS';
export const REQUEST_POST_COMMENTS = 'REQUEST_POST_COMMENTS';
export const RECEIVE_POST_COMMENTS = 'RECEIVE_POST_COMMENTS';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const GET_COMMENT_BY_POST_ID = 'GET_COMMENT_BY_POST_ID';
